syntax = "proto3";

package catalog.v1;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/SirNacou/ecommerce/services/catalog-service/gen/v1;catalogv1";

service CatalogService {
  rpc CreateCategory(CreateCategoryRequest) returns (CreateCategoryResponse);
  rpc ListCategories(ListCategoriesRequest) returns (ListCategoriesResponse);
  rpc CreateProduct(CreateProductRequest) returns (CreateProductResponse);
  rpc GetProduct(GetProductRequest) returns (GetProductResponse);
  rpc GetProductsByIds(GetProductsByIdsRequest) returns (GetProductsByIdsResponse);
  rpc ListProducts(ListProductsRequest) returns (ListProductsResponse);
  rpc GetStock(GetStockRequest) returns (GetStockResponse);
  rpc SetStock(SetStockRequest) returns (SetStockResponse);
  rpc ReserveStock(ReserveStockRequest) returns (ReserveStockResponse);
  rpc ReleaseStock(ReleaseStockRequest) returns (ReleaseStockResponse);
}

message Category {
  string id = 1;
  string name = 2;
  string slug = 3;
}

message Product {
  string id = 1;
  string category_id = 2;
  string name = 3;
  string description = 4;
  int64 price_cents = 5;
  google.protobuf.Timestamp created_at = 6;
}

message InventoryItem {
  string product_id = 1;
  int32 available_quantity = 2;
  int32 reserved_quantity = 3;
}

message CreateCategoryRequest {
  string name = 1;
  string slug = 2;
}

message CreateCategoryResponse {
  Category category = 1;
}

message ListCategoriesRequest {}

message ListCategoriesResponse {
  repeated Category categories = 1;
}

message CreateProductRequest {
  string category_id = 1;
  string name = 2;
  string description = 3;
  int64 price_cents = 4;
}

message CreateProductResponse {
  Product product = 1;
}

message GetProductRequest {
  string id = 1;
}

message GetProductResponse {
  Product product = 1;
}

message GetProductsByIdsRequest {
  repeated string ids = 1;
}

message GetProductsByIdsResponse {
  repeated Product products = 1;
}

message ListProductsRequest {
  int32 page_size = 1;
  string page_token = 2;
  string category_id = 3;
}

message ListProductsResponse {
  repeated Product products = 1;
  string next_page_token = 2;
}

message GetStockRequest {
  string product_id = 1;
}

message GetStockResponse {
  InventoryItem item = 1;
}

message SetStockRequest {
  string product_id = 1;
  int32 quantity = 2;
}

message SetStockResponse {
  InventoryItem item = 1;
}

message ReserveStockRequest {
  string reservation_id = 1; // Idempotency key (e.g. Order ID)
  string product_id = 2;
  int32 quantity = 3;
}

message ReserveStockResponse {
  bool success = 1;
  string message = 2;
}

message ReleaseStockRequest {
  string reservation_id = 1;
  string product_id = 2;
  int32 quantity = 3;
}

message ReleaseStockResponse {
  bool success = 1;
}