version: "2"

run:
  timeout: 5m
  tests: true
  relative-path-mode: cfg

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - exhaustruct
    - goconst
    - gocritic
    - misspell
    - revive

  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    govet:
      enable-all: true
      disable:
        - fieldalignment

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
