version: 3

includes:
  users:
    taskfile: ./services/user-service/Taskfile.yml
    dir: ./services/user-service
  catalog:
    taskfile: ./services/catalog-service/Taskfile.yml
    dir: ./services/catalog-service

tasks:
  default:
    cmds:
      - task --list

  infra:up:
    desc: "Start shared infrastructure (APISIX, etcd)"
    cmds:
      - docker compose -f docker-compose.infra.yml up -d

  up:all:
    desc: "Start entire platform"
    cmds:
      - task: infra:up
      - task: users:up

  buf:generate:
    desc: "Generate code from protobuf definitions"
    cmds:
      - buf generate
