apisix:
  node_listen: ${{APISIX_HTTP_PORT}}
  plugins:
    - cors
    - jwt-auth
    - key-auth
    - limit-req
    - limit-conn
    - limit-count
    - proxy-rewrite
    - request-id
    - response-rewrite
    - prometheus
    - file-logger

deployment:
  role: data_plane
  role_data_plane:
    config_provider: yaml
  admin:
    allow_admin:
      - 0.0.0.0/0
    admin_key:
      - name: "admin"
        key: ${{APISIX_ADMIN_KEY}}
        role: admin
