apisix:
  node_listen: 9080 # Gateway HTTP entry port

deployment:
  role: traditional
  role_traditional:
    config_provider: etcd
  admin:
    enable_admin_ui: true
    allow_admin:
      - 0.0.0.0/0 # Allow Admin API access from Docker network
    admin_key:
      - name: "admin"
        key: edd1c9f034335f136f87ad84b625c8f1 # Default APISIX admin API key
        role: admin
  etcd:
    host:
      - "http://etcd:2379" # Connect to the etcd container
    prefix: "/apisix"
    timeout: 30
