package postgres

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/SirNacou/ecommerce/services/catalog-service/internal/app"
	"github.com/SirNacou/ecommerce/services/catalog-service/internal/domain"
	"github.com/SirNacou/ecommerce/services/catalog-service/internal/infrastructure/persistence/postgres/db" // Generated by sqlc
)

type pgxUnitOfWork struct {
	pool *pgxpool.Pool
}

func NewUnitOfWork(pool *pgxpool.Pool) app.UnitOfWork {
	return &pgxUnitOfWork{pool: pool}
}

func (u *pgxUnitOfWork) Execute(ctx context.Context, fn func(store app.CatalogStore) error) error {
	tx, err := u.pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}

	defer func() {
		if p := recover(); p != nil {
			_ = tx.Rollback(ctx)
			panic(p)
		}
	}()

	// 1. Instantiates sqlc queries scoped strictly to this transaction (pgx.Tx)
	queries := db.New(tx)

	// 2. Pass transactional store handle to closure
	store := &catalogStore{
		tx:      tx,
		queries: queries,
	}

	if err := fn(store); err != nil {
		_ = tx.Rollback(ctx)
		return err
	}

	return tx.Commit(ctx)
}

type catalogStore struct {
	tx      pgx.Tx
	queries *db.Queries
}

// -----------------------------------------------------------------------------
// Products
// -----------------------------------------------------------------------------

func (s *catalogStore) CreateProduct(ctx context.Context, p *domain.Product) error {
	err := s.queries.CreateProduct(ctx, db.CreateProductParams{
		ID:            p.ID,
		CategoryID:    p.CategoryID,
		Name:          p.Name,
		Description:   p.Description,
		PriceCents:    p.PriceCents,
		StockQuantity: p.StockQuantity,
		CreatedAt:     p.CreatedAt,
		UpdatedAt:     p.UpdatedAt,
	})
	if err != nil {
		return fmt.Errorf("sqlc create product failed: %w", err)
	}

	return nil
}

func (s *catalogStore) GetProductByID(ctx context.Context, id uuid.UUID) (*domain.Product, error) {
	row, err := s.queries.GetProductByID(ctx, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, domain.ErrProductNotFound
		}
		return nil, fmt.Errorf("sqlc get product failed: %w", err)
	}

	// Map sqlc struct -> domain Entity
	return &domain.Product{
		ID:            row.ID,
		CategoryID:    row.CategoryID,
		Name:          row.Name,
		Description:   row.Description,
		PriceCents:    row.PriceCents,
		StockQuantity: row.StockQuantity,
		CreatedAt:     row.CreatedAt,
		UpdatedAt:     row.UpdatedAt,
	}, nil
}

func (s *catalogStore) ListProducts(ctx context.Context, categoryID *uuid.UUID, limit, offset int32) ([]*domain.Product, error) {
	rows, err := s.queries.ListProducts(ctx, db.ListProductsParams{
		Limit:      limit,
		Offset:     offset,
		CategoryID: categoryID,
	})
	if err != nil {
		return nil, fmt.Errorf("sqlc list products failed: %w", err)
	}

	products := make([]*domain.Product, 0, len(rows))
	for _, row := range rows {
		products = append(products, &domain.Product{
			ID:            row.ID,
			CategoryID:    row.CategoryID,
			Name:          row.Name,
			Description:   row.Description,
			PriceCents:    row.PriceCents,
			StockQuantity: row.StockQuantity,
			CreatedAt:     row.CreatedAt,
			UpdatedAt:     row.UpdatedAt,
		})
	}

	return products, nil
}

// -----------------------------------------------------------------------------
// Categories
// -----------------------------------------------------------------------------

func (s *catalogStore) CreateCategory(ctx context.Context, c *domain.Category) error {
	err := s.queries.CreateCategory(ctx, db.CreateCategoryParams{
		ID:        c.ID,
		Name:      c.Name,
		Slug:      c.Slug,
		CreatedAt: c.CreatedAt,
	})
	if err != nil {
		return fmt.Errorf("sqlc create category failed: %w", err)
	}

	return nil
}

func (s *catalogStore) GetCategoryByID(ctx context.Context, id uuid.UUID) (*domain.Category, error) {
	row, err := s.queries.GetCategoryByID(ctx, id)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, domain.ErrCategoryNotFound
		}
		return nil, fmt.Errorf("sqlc get category failed: %w", err)
	}

	return &domain.Category{
		ID:        row.ID,
		Name:      row.Name,
		Slug:      row.Slug,
		CreatedAt: row.CreatedAt,
	}, nil
}

func (s *catalogStore) ListCategories(ctx context.Context) ([]*domain.Category, error) {
	rows, err := s.queries.ListCategories(ctx)
	if err != nil {
		return nil, fmt.Errorf("sqlc list categories failed: %w", err)
	}

	categories := make([]*domain.Category, 0, len(rows))
	for _, row := range rows {
		categories = append(categories, &domain.Category{
			ID:        row.ID,
			Name:      row.Name,
			Slug:      row.Slug,
			CreatedAt: row.CreatedAt,
		})
	}

	return categories, nil
}
