// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateNotification(ctx context.Context, arg CreateNotificationParams) error
	GetNotificationByID(ctx context.Context, id uuid.UUID) (Notification, error)
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	ListNotificationsByUserID(ctx context.Context, arg ListNotificationsByUserIDParams) ([]Notification, error)
	MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error
	UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) error
}

var _ Querier = (*Queries)(nil)
