// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePayment(ctx context.Context, arg CreatePaymentParams) error
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error)
	GetPendingOutboxEvents(ctx context.Context, limit int32) ([]OutboxEvent, error)
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	MarkOutboxEventProcessed(ctx context.Context, id uuid.UUID) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) error
}

var _ Querier = (*Queries)(nil)
