// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreateProduct(ctx context.Context, arg CreateProductParams) error
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetProductByID(ctx context.Context, id uuid.UUID) (Product, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
