// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ClearCartItems(ctx context.Context, cartID uuid.UUID) error
	CreateCart(ctx context.Context, arg CreateCartParams) error
	GetCartByUserID(ctx context.Context, userID uuid.UUID) (Cart, error)
	GetCartItems(ctx context.Context, cartID uuid.UUID) ([]CartItem, error)
	RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) error
}

var _ Querier = (*Queries)(nil)
